#!/usr/bin/env python3
"""Apply tools/mass_budget.yaml to the generated inertials.

    python3 tools/mass_budget.py [package_dir]

Input : urdf/hexapod_properties.gen.xacro  (written by tools/gen.py from the STEP)
        tools/mass_budget.yaml             (print settings, materials, electronics, safety factor)
Output: urdf/hexapod_properties.xacro      (what hexapod.urdf.xacro includes)
        doc/mass_budget.md                 (table for chapter 3)

Per link the target mass is computed from the part list; the generated
inertial is then scaled by target / generated mass. Scaling keeps gen.py's
centre of mass and principal axes, which is exact when every part of the
link changes density by the same ratio and a close approximation otherwise
(servo mass is fixed while PETG changes) - re-run tools/gen.py with the STEP
for exact per-part values, then run this script again.
"""
from __future__ import annotations

import os
import re
import sys
import time

import yaml

LINKS = ("base", "coxa", "femur", "tibia", "foot")
NUM = r"[-+0-9.eE]+"


def link_mass(spec: dict, cfg: dict) -> tuple[float, list[tuple[str, int, float]]]:
    rows, total = [], 0.0
    for name, vol_cm3, material, fill, count in spec.get("printed", []):
        m = vol_cm3 * 1e-6 * cfg["materials"][material] * fill
        rows.append((f"{name} ({material}, fill {fill:.2f})", count, m))
        total += m * count
    for name, count in spec.get("fixed", []):
        m = cfg["fixed_mass_kg"][name]
        rows.append((name, count, m))
        total += m * count
    return total, rows


def scale_inertial(block: str, factor: float) -> str:
    def mass(match):
        return f'<mass value="{float(match.group(1)) * factor:.6g}"/>'

    def inertia(match):
        values = {k: float(v) * factor for k, v in re.findall(rf'(\w+)="({NUM})"', match.group(0))}
        return "<inertia " + " ".join(f'{k}="{v:.6g}"' for k, v in values.items()) + "/>"

    block = re.sub(rf'<mass value="({NUM})"/>', mass, block)
    return re.sub(r"<inertia [^>]*/>", inertia, block)


def main() -> int:
    pkg = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    cfg = yaml.safe_load(open(os.path.join(pkg, "tools", "mass_budget.yaml"), encoding="utf-8"))
    gen_path = os.path.join(pkg, "urdf", "hexapod_properties.gen.xacro")
    text = open(gen_path, encoding="utf-8").read()
    sf = float(cfg["safety_factor"])
    applies = set(cfg.get("safety_factor_applies_to", []))
    sf_links = sf if "links" in applies else 1.0
    sf_elec = sf if "electronics" in applies else 1.0

    report = []
    new_masses = {}
    for link in LINKS:
        target, rows = link_mass(cfg["links"][link], cfg)
        target_sf = target * sf_links
        old = float(re.search(rf'name="{link}_mass" value="({NUM})"', text).group(1))
        factor = target_sf / old
        text = re.sub(rf'(name="{link}_mass" value=")({NUM})(")', rf"\g<1>{target_sf:.6g}\g<3>", text)
        macro = re.search(rf'<xacro:macro name="{link}_inertial">.*?</xacro:macro>', text, re.S)
        text = text[: macro.start()] + scale_inertial(macro.group(0), factor) + text[macro.end():]
        new_masses[link] = target_sf
        report.append((link, old, target, target_sf, rows))

    electronics = {}
    for name, item in cfg["electronics"].items():
        factor = 1.0 if name == "battery" else sf_elec
        electronics[name] = (item["mass_kg"] * factor, item["mass_kg"], item["source"])
    props = "\n".join(
        f'  <xacro:property name="{name}_mass" value="{m:.6g}"/>  <!-- {raw * 1000:.0f} g x {m / raw:.2f}: {src} -->'
        for name, (m, raw, src) in electronics.items()
    )
    header = (
        "<!-- GENERATED by tools/mass_budget.py from hexapod_properties.gen.xacro (tools/gen.py) and\n"
        f"     tools/mass_budget.yaml on {time.strftime('%Y-%m-%d %H:%M')}. Do not edit: change the yaml and re-run. -->\n"
    )
    text = text.replace("<robot ", header + "<robot ", 1)
    text = text.replace("</robot>", "  <!-- ===== Electronics masses (used by electronics.xacro / sensors.xacro) ===== -->\n"
                        + props + "\n</robot>")
    open(os.path.join(pkg, "urdf", "hexapod_properties.xacro"), "w", encoding="utf-8").write(text)

    legs = 6 * sum(new_masses[k] for k in ("coxa", "femur", "tibia", "foot"))
    body = new_masses["base"]
    elec_total = sum(m for m, _, _ in electronics.values())
    total = body + legs + elec_total
    lines = [
        "# Mass budget (generated by tools/mass_budget.py)",
        "",
        f"Safety factor {sf:.2f} on links and estimated electronics (not on the measured battery). "
        "Print: Bambu Lab A1, 0.4 mm nozzle, 4 walls, 40 % honeycomb; fill factor per part from a shell model (t = 1.5 mm).",
        "",
        "| Link | gen.py (fill 0.70) g | Budget g | x SF g | x count |",
        "|---|---:|---:|---:|---:|",
    ]
    for link, old, target, target_sf, _ in report:
        count = 1 if link == "base" else 6
        lines.append(f"| {link} | {old * 1000:.1f} | {target * 1000:.1f} | {target_sf * 1000:.1f} | {target_sf * count * 1000:.1f} |")
    lines += ["", "| Electronics | Mass in model g | Source |", "|---|---:|---|"]
    for name, (m, raw, src) in electronics.items():
        lines.append(f"| {name} | {m * 1000:.1f} | {src} |")
    lines += ["", f"**Total: {total * 1000:.0f} g** (body {body * 1000:.0f} g, 6 legs {legs * 1000:.0f} g, electronics {elec_total * 1000:.0f} g)", ""]
    lines += ["## Parts per link (before safety factor)", ""]
    for link, _, target, _, rows in report:
        lines.append(f"- **{link}** ({target * 1000:.1f} g): " + "; ".join(f"{n} x{c} = {m * c * 1000:.1f} g" for n, c, m in rows))
    open(os.path.join(pkg, "doc", "mass_budget.md"), "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print("\n".join(lines))
    return 0


if __name__ == "__main__":
    sys.exit(main())
